include(ExternalProject)
include(${CMAKE_SOURCE_DIR}/cmake/rtklib.cmake)
include(${CMAKE_SOURCE_DIR}/cmake/libevent.cmake)
include(${CMAKE_SOURCE_DIR}/cmake/pugixml.cmake)
if(ENABLE_STREAM_LOG)
include(${CMAKE_SOURCE_DIR}/cmake/spdlog.cmake)
endif()
